# Generated by Django 4.1.7 on 2023-09-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('education_level', models.CharField(choices=[('6th', '6th Grade'), ('7th', '7th Grade'), ('8th', '8th Grade'), ('9th', '9th Grade'), ('10th', '10th Grade'), ('Intermediate', 'Intermediate')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
