# Generated by Django 4.1.7 on 2023-09-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerbot', '0002_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_datavalues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('education', models.CharField(choices=[('6th', '6th Grade'), ('7th', '7th Grade'), ('8th', '8th Grade'), ('9th', '9th Grade'), ('10th', '10th Grade'), ('intermediate', 'Intermediate')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
