# Generated by Django 4.1.7 on 2023-09-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerbot', '0003_user_datavalues_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('education', models.CharField(choices=[('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('Intermediate', 'Intermediate')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='User_datavalues',
        ),
    ]
